import { chromium } from "playwright";
import { startFixtureSites } from "@steplight/fixtures-site";
import { collectPageScan, computeTokenStats } from "@steplight/core";
const site = await startFixtureSites();
const b = await chromium.launch();
const p = await b.newPage();
await p.goto(`${site.url}/noisy.html`);
const scan = await p.evaluate(collectPageScan);
console.log(scan.dom.nodes.length, scan.text.length);
console.log(scan.dom.nodes.map(n => `${n.landmark ?? "-"} ${n.display} ${n.text.length}`).join("\n"));
console.log(computeTokenStats(scan));
await b.close(); await site.close();
